// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table Book {
  id integer [primary key]
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
  name string
  author string
  publication string
}
